# Generated by Django 3.1.3 on 2020-11-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payload',
            name='decrypted_message',
            field=models.CharField(default='', max_length=8192),
            preserve_default=False,
        ),
    ]
