# Generated by Django 3.1.3 on 2020-11-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_payload_decrypted_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payload',
            name='message',
        ),
        migrations.AddField(
            model_name='payload',
            name='encrypted_message',
            field=models.TextField(default='', max_length=8192),
            preserve_default=False,
        ),
    ]
