# Generated by Django 3.1.3 on 2020-11-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201118_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payload',
            old_name='encrypted_message',
            new_name='message',
        ),
    ]
